language: python
python: 3.6
dist: trusty
services: docker
filter_secrets: false
os: linux

cache:
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/.cache/pip

env:
  global:
  - REPO_DIR=rasterio
  - BUILD_COMMIT=4491f2d
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - USE_CCACHE=1

addons:
  artifacts:
    paths:
    - $(ls wheelhouse/*.whl)

jobs:
  include:
  - name: "Python 3.9 ARM64 linux"
    os: linux
    arch: arm64
    env:
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.9
    - DEBUG_PRINT=1
    - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
  - name: "Python 3.6 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.15.4
    - NP_TEST_DEP=numpy==1.15.4
  - name: "Python 3.7 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.15.4
    - NP_TEST_DEP=numpy==1.15.4
  - name: "Python 3.8 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.5
    - NP_TEST_DEP=numpy==1.17.5
  - name: "Python 3.9 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.9
    - NP_BUILD_DEP=numpy==1.19.4
    - NP_TEST_DEP=numpy==1.19.4
  - name: "Python 3.6 osx"
    os: osx
    language: generic
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.15.4
    - NP_TEST_DEP=numpy==1.15.4
  - name: "Python 3.7 osx"
    os: osx
    language: generic
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.15.4
    - NP_TEST_DEP=numpy==1.15.4
  - os: osx
    language: generic
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.5
    - NP_TEST_DEP=numpy==1.17.5
    - MB_PYTHON_OSX_VER=10.9
  - os: osx
    language: generic
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.5
    - NP_TEST_DEP=numpy==1.17.5
    - MB_PYTHON_OSX_VER=10.9
  - os: osx
    language: generic
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.9
    - NP_BUILD_DEP=numpy==1.19.4
    - NP_TEST_DEP=numpy==1.19.4
    - MB_PYTHON_OSX_VER=10.9

before_install:
    - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
    - BUILD_DEPENDS="$NP_BUILD_DEP cython==0.29.21 wheel==0.34.2"
    - TEST_DEPENDS="$NP_TEST_DEP attrs==19.1.0 pytest==4.0.2 click==7.0.0 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2 $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT
    - ls -l ${TRAVIS_BUILD_DIR}/wheelhouse/
    - unzip -l ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl

script:
    - install_run $PLAT
