env:
    global:
        - REPO_DIR=rasterio
        # Commit from your-project that you want to build
        - BUILD_COMMIT=1.0.3
        # pip dependencies to _build_ your project
        - BUILD_DEPENDS="Cython numpy"
        # pip dependencies to _test_ your project.  Include any dependencies
        # that you need, that are also specified in BUILD_DEPENDS, this will be
        # a separate install.
        - TEST_DEPENDS="matplotlib numpy pytest"
        - PLAT=x86_64
        - UNICODE_WIDTH=32
        - NP_BUILD_DEP="numpy==1.10.0"
        - NP_TEST_DEP="numpy==1.10.0"
        - ARTIFACTS_BUCKET="rasterio-wheels"

addons:
    artifacts: true
        paths:
            - $(ls wheels/*.whl)

language: python
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.7
#         - NP_BUILD_DEP=numpy==1.14.5
#         - NP_TEST_DEP=numpy==1.14.5
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.7
#         - PLAT=i686
#         - NP_BUILD_DEP=numpy==1.14.5
#         - NP_TEST_DEP=numpy==1.14.5
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.5
#         - NP_BUILD_DEP=numpy==1.10.4
#         - NP_TEST_DEP=numpy==1.10.4
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.5
#         - PLAT=i686
#         - NP_BUILD_DEP=numpy==1.10.4
#         - NP_TEST_DEP=numpy==1.10.4
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.6
#         - NP_BUILD_DEP=numpy==1.11.3
#         - NP_TEST_DEP=numpy==1.11.3
#     - os: linux
#       env:
#         - MB_PYTHON_VERSION=3.6
#         - PLAT=i686
#         - NP_BUILD_DEP=numpy==1.11.3
#         - NP_TEST_DEP=numpy==1.11.3
#     - os: osx
#       language: generic
#       env:
#         - MB_PYTHON_VERSION=3.5
#         - NP_BUILD_DEP=numpy==1.10.4
#         - NP_TEST_DEP=numpy==1.10.4
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.11.3
        - NP_TEST_DEP=numpy==1.11.3
#     - os: osx
#       language: generic
#       env:
#         - MB_PYTHON_VERSION=3.7
#         - NP_BUILD_DEP=numpy==1.14.5
#         - NP_TEST_DEP=numpy==1.14.5

before_install:
    - BUILD_DEPENDS="$NP_BUILD_DEP"
    - TEST_DEPENDS="$NP_TEST_DEP rasterio $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
